### PR TITLE
fix remember-me checkbox

### LINKED ISSUE #279: Authentication is lost when closing the browser
For some reason, if a user authenticates in the UI and then closes the UI tab in his browser, he won't be recognized next time he opens the UI even though he had checked "remember me".
The issue occurs in the demo instance (updated last friday) and in my own instance (up-to-date on master). This seems a quite recent bug.

### PR DESCRIPTION
**Pull request by ginold**
fixes #279

### CODE REVIEW

**Comment by gberaudo** [comment]
According to https://docs.angularjs.org/api/ng/directive/ngInit the preferred way is to change
the controller.

File: c2corg_ui/static/js/auth/auth.js [hunk 1]
```diff
@@ -55,6 +55,12 @@ app.AuthController = function($scope, appApi, appAuthentication,
    */
   this.scope_ = $scope;
 
+  if (!this.scope_['login']) {
+    this.scope_['login'] = {};
+  }
```
Comment (asaunier) [inline c2corg_ui/static/js/auth/auth.js]: I think we rather write
```
this.scope_['login'] = this.scope_['login'] || {};
```

**Comment by asaunier** [comment]
A minor comment. Anyway it looks good to me now.

By the way @ginold add a comment when you make changes to a PR, else no one will notice :P

File: c2corg_ui/static/js/auth/auth.js (hunk 1 above)
Comment (gberaudo) [inline c2corg_ui/static/js/auth/auth.js]: Can it be simplified to `this.scope_['login'] = {'remember': true};`?

Comment (ginold) [inline c2corg_ui/static/js/auth/auth.js]: make up your minds and tell me which solution is better :ideograph_advantage:

Comment (tsauerwein) [inline c2corg_ui/static/js/auth/auth.js]: I prefer @gberaudo variant, it's less confusing.

Comment (tsauerwein) [inline c2corg_ui/static/js/auth/auth.js]: Unless if there is other stuff stored in `this.scope_['login']`?

Comment (ginold) [inline c2corg_ui/static/js/auth/auth.js]: yep, there are login.password, .remember and .username

Comment (tsauerwein) [inline c2corg_ui/static/js/auth/auth.js]: Ok, then I would prefer your initial proposition. :)

Comment (gberaudo) [inline c2corg_ui/static/js/auth/auth.js]: I tested my solution and it works as-is; there is no need to initialize the other fields in the controller.

Comment (asaunier) [inline c2corg_ui/static/js/auth/auth.js]: I think @gberaudo solution is OK since we set "login" in the scope with the default values (remember: true) before actually setting the username/password from the form.

Comment (asaunier) [inline c2corg_ui/static/js/auth/auth.js]: @ginold Make your choice and merge, thanks :)
