### PR TITLE
Route and outing editing fixes

### LINKED ISSUE #510: Document creation: incorrect default lang
When creating a new document (route/outing/...), the language selected by default in the editing form is "english" whereas my interface is in french => the default language should be the same than the interface language.

### PR DESCRIPTION
**Pull request by ginold**
related to  #403 - via ferrata glacier gear showing up
related to #403  - associated routes stlye
related to #509 - rating block via ferrata not showing up
fixes #510
related to #514 - glacier_gear not displayed in route view pages
related to  #516 - participant_count field
related to #531

`partial_trip` and `public_transportation` checkboxes left align

### CODE REVIEW

**Comment by asaunier** [comment]
I feel a bit uncomfortable about the cookies approach but if you think we cannot use a ``gettextCatalog`` solution, than go for it and merge.

**Comment by ginold** [comment]
Clearly if we can figure out how to do it with `gettextCatalog` it would be better, but I didn't manage to do so. At the end, how does `gettextCatalog` work? isn't it getting the value somewhere from cookies too?

**Comment by ginold** [comment]
I will add 2 small commits for two issues created and we can merge.

**Comment by tsauerwein** [comment]
> At the end, how does gettextCatalog work? isn't it getting the value somewhere from cookies too?

Take a look at [lang.js](https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/lang.js#L95-L96):

```
 var lang = this.cookies_.get('interface_lang') ||
      ngeoGetBrowserLanguage(this['langs']) || 'fr';
```

The problem is that the language controller seems to be initialized after you try to access the language. It would be better to wrap the logic which manages the locale into a service, and use this service in the language controller and here.

**Comment by ginold** [comment]
@asaunier I added 2 commits and for me it's ok to be reviewed and merged.

File: c2corg_ui/static/js/documentediting.js [hunk 1]
```diff
@@ -74,6 +75,12 @@ app.DocumentEditingController = function($scope, $element, $attrs, gettextCatalo
   this.ngeoLocation_ = ngeoLocation;
 
   /**
+   * @type {angular.$cookies}
+   * @private
+   */
+  this.cookies_ = $cookies;
```
Comment (asaunier) [inline c2corg_ui/static/js/documentediting.js]: This property is not needed since used in the constructor => you can use ``$cookies`` directly.

File: c2corg_ui/templates/route/helpers/detailed_route_attributes.html [hunk 2]
```diff
@@ -211,3 +211,21 @@
   </div>
   % endif
 </%def>
+
+## GLACIER GEAR
+<%def name="get_route_glacier_gear(route)">\
+  % if route.get('glacier_gear'):
+  <div class="name-icon-value"
+       ng-click="detailsCtrl.openTab($event)">
+      <h4><span translate>gear</span><span class="glyphicon glyphicon-menu-right"></span></h4>
```
Comment (asaunier) [inline c2corg_ui/templates/route/helpers/detailed_route_attributes.html]: Indentation is not correct here.

**Comment by asaunier** [comment]
I agree using a lang service would be an appropriate solution but could be done separately so that we don't wait too much to merge the fixes of this PR.
OK for me to merge the PR when the minor comments I just reported are fixed.

File: c2corg_ui/static/js/documentediting.js (hunk 1 above)
Comment (ginold) [inline c2corg_ui/static/js/documentediting.js]: If I write `$cookies_.get('interface_lang');` i get  `ERROR - variable $cookies_ is undeclared
`

File: c2corg_ui/static/js/documentediting.js [hunk 3]
```diff
@@ -164,7 +165,7 @@ app.DocumentEditingController = function($scope, $element, $attrs, gettextCatalo
       );
     } else if (!this.id_) {
       // new doc lang = user interface lang
-      this.scope[this.modelName]['locales'][0]['lang'] = this.lang_;
+      this.scope[this.modelName]['locales'][0]['lang'] = $cookies_.get('interface_lang');
```
Comment (asaunier) [inline c2corg_ui/static/js/documentediting.js]: Should be ``$cookies``, not ``$cookies_``.

**Comment by ginold** [comment]
Ok, I will be merging pretty soon. I just added one more commit (i promise it's the last one :P) for the issue that has just been created #531  - it was not a big deal to solve it.

**Comment by asaunier** [comment]
:+1:
